[apache] add automation script
endoflife-date/release-data pull request #122
Opened 2023-07-16 14:32 UTC by dadav

This script fetches informations from the https://github.com/apache/httpd repo.
Every branch formated like 2.4.x has a `STATUS` file which contains a version history.
Not every version was released, so I filter the lines with `(?:Released|Announced)` to get the released versions only (they were not rly consistent in the passed with the wording, it seems better now).
They use the format `Month Day, Year` and I try to parse the date and convert it to the required format. Dates which fail this process are filtered out.

2023-07-23 20:01 UTC, marcwrobel approved these changes
LGTM, thanks @dadav.

I have updated the script to : 

- make it a little bit more linear / easier to read (at least for me ;)),
- make it fail if an unknown date format is used (we want to be aware of it)
- incorporate the PR description as a comment in the script.

2023-07-23 20:08 UTC, marcwrobel commented
Will have to test the script before merging it : I think the name should be apache-http-server and I want to check the impacts of the script to the current product page.

2023-07-23 20:15 UTC, marcwrobel commented
Just checked, the diff will be :

```diff
diff --git i/products/apache-http-server.md w/products/apache-http-server.md
index a7c408e1..e654687c 100644
--- i/products/apache-http-server.md
+++ w/products/apache-http-server.md
@@ -33,13 +33,13 @@ releases:
     latestReleaseDate: 2017-07-11
 
 -   releaseCycle: "2.0"
-    releaseDate: 2002-04-06
+    releaseDate: 2007-09-07
     eol: 2013-07-10
     latest: "2.0.65"
     latestReleaseDate: 2013-07-10
 
 -   releaseCycle: "1.3"
-    releaseDate: 1998-06-06
+    releaseDate: 2001-01-29
     eol: 2010-02-03
     latest: "1.3.42"
     latestReleaseDate: 2010-02-03
```

Looks like we will have to do something for keeping those release date:

- either parsing them if they are available on the repository,
- or inject them manually (like I did in https://github.com/endoflife-date/release-data/pull/111/files).

Will try to have a look next week.

2023-07-23 20:19 UTC, marcwrobel approved these changes
Release dates for 1.3 and 2.0 must be checked and kept as is if they are correct.

2023-07-23 20:20 UTC, marcwrobel requested changes
Release dates for 1.3 and 2.0 must be checked and kept as is if they are correct.

2023-07-25 19:57 UTC, marcwrobel commented
Current release dates are in line with https://en.wikipedia.org/wiki/Apache_HTTP_Server, they must be kept as is.

2023-07-25 20:52 UTC, marcwrobel commented
Just pushed an update, the expected diff is now :

```diff
diff --git i/products/apache-http-server.md w/products/apache-http-server.md
index a7c408e1..ac4dff61 100644
--- i/products/apache-http-server.md
+++ w/products/apache-http-server.md
@@ -33,16 +33,16 @@ releases:
     latestReleaseDate: 2017-07-11
 
 -   releaseCycle: "2.0"
-    releaseDate: 2002-04-06
+    releaseDate: 2002-04-05
     eol: 2013-07-10
     latest: "2.0.65"
-    latestReleaseDate: 2013-07-10
+    latestReleaseDate: 2013-07-09
 
 -   releaseCycle: "1.3"
-    releaseDate: 1998-06-06
+    releaseDate: 1998-06-01
     eol: 2010-02-03
     latest: "1.3.42"
-    latestReleaseDate: 2010-02-03
+    latestReleaseDate: 2010-02-02
```

Think we are close enough to the actual release dates to consider it OK. WDYT @dadav and @captn3m0 ?

2023-07-25 20:58 UTC, marcwrobel approved these changes
LGTM with the changes

2023-07-26 03:39 UTC, captn3m0 approved these changes
LGTM.

2023-07-26 04:34 UTC, merged